# Generated by Django 5.1 on 2026-07-16 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('question', models.TextField()),
                ('generated_sql', models.TextField()),
                ('sql_approved', models.BooleanField(default=False)),
                ('execution_time_ms', models.IntegerField(null=True)),
                ('result_summary', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('anomaly_type', models.CharField(max_length=32)),
                ('severity', models.CharField(max_length=16)),
                ('summary', models.TextField()),
                ('raw_metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255)),
                ('score', models.FloatField()),
                ('risk_band', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=16)),
                ('factors', models.JSONField(default=dict)),
                ('flagged_patterns', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('payment_created', 'Payment Created'), ('duplicate_detected', 'Duplicate Detected'), ('payment_failed', 'Payment Failed'), ('stale_lock_recovered', 'Stale Lock Recovered'), ('payload_mismatch', 'Payload Mismatch (422)')], db_index=True, max_length=32)),
                ('payment_id', models.IntegerField(db_index=True, null=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('api_key_prefix', models.CharField(max_length=32)),
                ('status_code', models.IntegerField()),
                ('latency_ms', models.IntegerField(null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='ai_intellig_event_t_498e01_idx'), models.Index(fields=['idempotency_key', 'created_at'], name='ai_intellig_idempot_cfb62f_idx')],
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('timeline', models.JSONField(default=list)),
                ('affected_endpoints', models.JSONField(default=list)),
                ('probable_cause', models.TextField()),
                ('impact_summary', models.TextField()),
                ('recommended_fixes', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('published', 'Published')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_intelligence.paymentevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FailureAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_cause', models.CharField(choices=[('timeout', 'Timeout'), ('db_lock', 'Database Lock'), ('network_retry', 'Network Retry'), ('duplicate_request', 'Duplicate Request'), ('gateway_failure', 'Gateway Failure'), ('server_error', 'Server Error'), ('unknown', 'Unknown')], max_length=32)),
                ('confidence', models.FloatField()),
                ('explanation_text', models.TextField()),
                ('suggested_fixes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='failure_analysis', to='ai_intelligence.paymentevent')),
            ],
        ),
        migrations.CreateModel(
            name='DuplicateExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation_text', models.TextField()),
                ('reasoning_factors', models.JSONField(default=dict)),
                ('llm_model_used', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_explanation', to='ai_intelligence.paymentevent')),
            ],
        ),
    ]
