# Generated by Django 5.1 on 2026-07-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentevent',
            name='payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
